name: JQ to Osaka
favicon: null
layout_spectrum: 0.3396465552505106
typography_spectrum: 0.512421072460711
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5573146170936525
  lightness: 0.9052630427759141
  saturation: 0.9380913514178246
  rhythmicContrast: 0.7852115172427148
purpose: []
