name: JQ to Osaka
favicon: null
layout_spectrum: 0.50422
typography_spectrum: 0.75091
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7fbfe'
    - '#020202'
    - '#c0c1bc'
    - '#828685'
    - '#4c4d48'
  brandStrength: 0
  lightness: 1
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
